# Generated by Django 3.2.1 on 2021-10-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunity', '0004_vacancy_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied',
            name='list',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='tunity.vacancy'),
        ),
    ]
